### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by chonming** [c-sommer/primitect#3]
hi, 

I'm interested to understand your work to detect shape in point cloud.  However, run into compilation errors in Ubuntu.  

primitect/cpp/include/objects/Plane.h:115:24: error: expected primary-expression before ‘(’ token
         return Plane<U>(n_.cast<U>(), U(d_), this->rep_.cast<U>());

...

Regards,
Chon Ming

**Comment by c-sommer** [comment]
Hi Chon Ming,
the code compiles and runs successfully for me on Ubuntu 18.04 with gcc 7.5.0. - could you try with these? Or which Ubuntu version and compiler are you using?
Best,
Christiane
